### PR TITLE
coveralls badge

### PR DESCRIPTION
**Pull request by DonBrinn**

### CODE REVIEW

**Comment by bemailloux** [comment]
Just wondering about the scripts here:
```
"scripts": {
    "code:coverage": "nyc report --reporter=cobertura --reporter=html",
    "code:coverage:report": "nyc report --reporter=text-lcov | coveralls",
    "code:lint": "eslint --ignore-path .gitignore .",
    "precode:test": "npm run code:lint",
    "code:test": "nyc --root src mocha --recursive test",
    "postcode:test": "npm run code:coverage",
    "test": "npm run code:test"
  },
```

Does this actually send the report to coveralls? I don't see `npm run code:coverage:report` called anywhere (but I'm not sure if that's supposed to happen automatically).

**Comment by bemailloux** [comment]
Oh the repo has to be added to coveralls.io first oops

**Comment by DonBrinn** [comment]
> Does this actually send the report to coveralls?

Thanks, that was the problem.

**Comment by DonBrinn** [comment]
CI failure:
```
/home/circleci/project/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

That's strange, because I did add the repo to coveralls.io:  https://coveralls.io/github/Brightspace/service-now

**Comment by DonBrinn** [comment]
Looks like a token is needed: https://github.com/lemurheavy/coveralls-public/issues/632#issuecomment-148815369

**Comment by bemailloux** [comment]
> Looks like a token is needed: lemurheavy/coveralls-public#632 (comment)

Ah I see - for SSR we're only reporting via the coveralls maven plugin - that's why there's no token that appears in the JS code.

**Pull request merged**
